# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
dist: xenial
language: r
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

before_install:
  - nvm install 8
  - npm install netlify-cli -g
  - fc-cache -fv
  - mkdir public

script:
  - Rscript -e 'blogdown::install_hugo()'
  - Rscript static/files/create_pub_md/bibtex_2academic.R
  - Rscript -e 'blogdown::build_site(method = "html")'

after_success:
  -  sh deploy.sh
