# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: false
branches:
  only:
    - master
cache:
  packages: true
  directories:
  - $HOME/.npm

before_install:
  - nvm install 8
  - npm install netlify-cli -g
  - Rscript -e 'install.packages("blogdown")'
  - Rscript -e 'blogdown::install_hugo()'

script:
  - Rscript -e 'blogdown::build_site()'

deploy:
  provider: script
  script: netlify deploy -a $NETLIFYKEY
  skip_cleanup: true
