baseurl: /
languageCode: en-US
title: Adam H. Sparks
theme: hermit-v2
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Biometry, agricultural data analysis, agriculture systems and plant disease modelling, and professional cat herding
  favicon: favicon.ico
  logo:
    alt: Logo
    height: 50
    url: img/noun-welding-3214348
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: "catppuccin-frappe"
    tabWidth: 4
