baseurl                 = "https://adamhsparks.com/"     # Your domain name. Must end with "/"
languageCode            = "en-au"
isMultilingual          = false
title                   = "Adam H. Sparks"
theme                   = "hugo-theme-sam"
pygmentsStyle           = "tango"          # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
#googleAnalytics         = ""           # Tracking code, eg. "UA-111111111-1"
ignoreFiles             = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "blogdown$", "external_data$", "\\.knit\\.md$", "\\.utf8\\.md$"]
uglyURLs                = true

[markup.goldmark.renderer]
unsafe = true

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "adam h sparks"

# Metadata
    description         = "Adam H. Sparks' personal website" # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/twitter-card.png"           # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/about/"
    text = "adam h sparks"

[[params.mainMenu]]
    link = "https://docs.google.com/viewer?url=https://github.com/adamhsparks/AHSparks_CV/raw/main/docs/Adam_H_Sparks_CV.pdf"
    text = "cv"

[[params.mainMenu]]
    link = "/code/"
    text = "code"

[[params.mainMenu]]
    link = "/post/"
    text = "blog"

[[params.mainMenu]]
    link = "/contact/"
    text = "contact"

[[params.mainMenu]]
    link = "/research/"
    text = "research"
