baseurl                 = "https://adamhsparks.github.io/"     # Your domain name. Must end with "/"
languageCode            = "en-au"
isMultilingual          = false
title                   = "Adam H. Sparks"
theme                   = "dimension"
pygmentsUseClasses      = true
pygmentsStyle           = "tango"          # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
ignoreFiles             = ['\.Rmd$', '_files$', '_cache$', '\.knit\.md$', '\.utf8\.md$']
uglyURLs                = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"

# Metadata
    description         = "Adam H. Sparks" # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/twitter-card.png"           # Image that shows on Twitter cards and OpenGraph links
