baseurl: /
languageCode: en-US
title: Adam H. Sparks
theme: hermit-v2
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - index\\.html
  - about\\.html
  - static/blog/\\*_files/
  - README
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: Posts
      url: /blog/
    - name: Research
      url: /research/
    - name: Code
      url: /code/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Biometry, agricultural data analysis, systems and plant disease modelling, and professional cat herding
  favicon: favicon.ico
  logo:
    alt: Logo
    height: 50
    url: img/noun-welding-3214348
    width: 50
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
    - julia
    - python
  highlightjsTheme: catppuccin-macchiato
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    style: "catppuccin-macchiato"
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 4
