baseurl                 = "https://adamhsparks.com/"     # Your domain name. Must end with "/"
languageCode            = "en-au"
isMultilingual          = false
title                   = "Adam H. Sparks"
theme                   = "sam"
pygmentsStyle           = "bw"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
#googleAnalytics         = ""              # Tracking code, eg. "UA-111111111-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "adam h sparks"

# Metadata
    description         = "Adam H. Sparks' personal website" # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/twitter-card.png"           # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/about"
    text = "adam h sparks"

[[params.mainMenu]]
    link = "/code"
    text = "code"

[[params.mainMenu]]
    link = "/contact"
    text = "contact"

[[params.mainMenu]]
    link = "/research"
    text = "research"
